version: 2
updates:
  - package-ecosystem: gomod
    target-branch: main
    directory: /
    schedule:
      interval: weekly
      day: monday
      timezone: Australia/Sydney
    cooldown:
      default-days: 1
    groups:
      go-dependencies:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    target-branch: main
    directory: /
    schedule:
      interval: weekly
      day: monday
      timezone: Australia/Sydney
    cooldown:
      default-days: 1
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-patch"
    groups:
      github-actions:
        patterns:
          - "*"
